spring:
  application:
    name: config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/luozhix/spring-cloud-config.git
          username: null
          password: null
          basedir: c:/项目/basedir
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management: 
  endpoints:
    web:
      exposure: 
        include: "*"
          
      #exposure: 
       # include: bus-refresh
       